services:

  php:
    build:
      context: .
      dockerfile: dockerfiles/dockerfile

    container_name: php_pin

    working_dir: /var/www/html

    volumes:
      - ./:/var/www/html



  nginx:

    image: nginx:latest

    container_name: laravel_nginx_pin

    ports:
      - "8080:80"

    volumes:
      - ./:/var/www/html
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php
